# Generated by Django 5.1.2 on 2025-11-16 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_date', models.DateField(help_text='Logical date of the dataset (usually the most recent incident date).')),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-batch_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=64, unique=True)),
                ('model_name', models.CharField(max_length=128)),
                ('algorithm', models.CharField(max_length=128)),
                ('stage', models.CharField(choices=[('training', 'Training'), ('validation', 'Validation'), ('testing', 'Testing'), ('production', 'Production Shadow')], default='training', max_length=32)),
                ('target_variable', models.CharField(default='incidents', max_length=128)),
                ('training_window', models.CharField(blank=True, max_length=64)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EvaluationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_of', models.DateField(help_text='Week ending or starting date for evaluation.')),
                ('audience', models.CharField(help_text='Executive, Command, Field, Analyst', max_length=64)),
                ('metric_name', models.CharField(max_length=128)),
                ('expected_value', models.FloatField(blank=True, null=True)),
                ('observed_value', models.FloatField(blank=True, null=True)),
                ('narrative', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-week_of', 'audience'),
                'unique_together': {('week_of', 'audience', 'metric_name')},
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(blank=True, max_length=64)),
                ('district', models.CharField(blank=True, max_length=64)),
                ('beat', models.CharField(blank=True, max_length=32)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('offense_category', models.CharField(blank=True, max_length=255)),
                ('priority', models.CharField(blank=True, max_length=64)),
                ('location_type', models.CharField(blank=True, max_length=255)),
                ('incident_datetime', models.DateTimeField()),
                ('incident_date', models.DateField()),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('day', models.PositiveSmallIntegerField()),
                ('day_of_week', models.CharField(blank=True, max_length=16)),
                ('hour', models.PositiveSmallIntegerField(default=0)),
                ('minute', models.PositiveSmallIntegerField(default=0)),
                ('iso_week', models.PositiveSmallIntegerField(default=0)),
                ('quarter', models.PositiveSmallIntegerField(default=0)),
                ('time_of_day_label', models.CharField(blank=True, max_length=32)),
                ('business_hours_flag', models.BooleanField(default=False)),
                ('calendar_month_label', models.CharField(blank=True, max_length=16)),
                ('narrative_date', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='analytics.importbatch')),
            ],
            options={
                'ordering': ('-incident_datetime',),
                'indexes': [models.Index(fields=['incident_date'], name='analytics_i_inciden_0fb1d9_idx'), models.Index(fields=['beat'], name='analytics_i_beat_d89730_idx'), models.Index(fields=['district'], name='analytics_i_distric_893b65_idx'), models.Index(fields=['offense_category'], name='analytics_i_offense_1da6de_idx')],
            },
        ),
    ]
